name: Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-msvc:
    name: Build with MSVC
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build --config Release

  build-mingw:
    name: Build with MinGW
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Build with Make
        run: make
